name: Move to mythrex.github.io

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Push to mythrex.github.io
    runs-on: ubuntu-latest

    steps:
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      # - name: Install
      #   run: npm install
      # - name: Install Vue
      #   run: npm install @vue/cli
      # - name: Build
      #   run: npm run build --if-present
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dist"
          destination-github-username: "mythrex"
          destination-repository-name: "mythrex.github.io"
          user-email: shivam.kaushik73@gmail.com
